openapi: 3.0.1
info:
  title: Mi API Contract First
  version: 1.0.0
paths:
  /saludo:
    get:
      summary: Obtener saludo
      operationId: getSaludo
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: string
