openapi: 3.0.1
info:
  title: Mi API Contract First
  version: 1.0.0
paths:
  /saludo:
    get:
      summary: Obtener saludo
      operationId: getSaludo
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: string
  /paises:
    get:
      summary: Listar todos los países
      operationId: listarTodos
      responses:
        '200':
          description: Lista de todos los países
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pais'
components:
  schemas:
    Pais:
      type: object
      properties:
        id:
          type: integer
          format: int64
        pais:
          type: string
        capital:
          type: string
        codigo:
          type: string